### ISSUE TITLE
Convert c3d to smpl

### ISSUE THREAD

**Issue by usamatariq70** [nghorbani/moshpp#1]
Hi,

Thank you for making this repository. Can you please guide me how I can convert c3d file to smpl file using this repository. I am unable to find any relevant tutorial.

Thank you

**Comment by nghorbani** [comment]
Hi, this repository is meant to be a tool used by the main interface which the [SOMA](https://github.com/nghorbani/soma) code. For the specific case where you have labeled mocap and want to get fitted bodies you can use this tutorial:
https://github.com/nghorbani/soma/blob/main/src/tutorials/solve_labeled_mocap.ipynb
